services:
  memory-server:
    build: .
    container_name: memory_mcp_server
    environment:
      # Neo4j connection via Docker network
      NEO4J_URI: neo4j://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      MEMORY_FILE_PATH: /app/data/memory.json
      NODE_ENV: production
      # Disable progress bars that interfere with JSON-RPC
      NPM_CONFIG_PROGRESS: "false"
    volumes:
      - memory_fallback_data:/app/data  # Mount to /app/data instead of /app/dist
      - ./logs:/app/logs  # Mount logs directory
    networks:
      - neo4j_neo4j-network  # Connect to existing Neo4j network
    stdin_open: true
    tty: true
    entrypoint: []  # Clear Dockerfile ENTRYPOINT
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

networks:
  neo4j_neo4j-network:
    external: true  # Use existing Neo4j network

volumes:
  memory_fallback_data:

